[phases.setup]
nixPkgs = ['nodejs_18', 'python3']

[phases.install]
cmds = ['npm ci --only=production --legacy-peer-deps']

[phases.build]
cmds = ['cd client && npm ci && npm run build']

[start]
cmd = 'NODE_ENV=production npm start'
